#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DB_HOST="${SETUP_DB_HOST:-localhost}"
DB_PORT="${SETUP_DB_PORT:-5432}"
DB_ADMIN_USER="${SETUP_DB_USER:-postgres}"
DB_ADMIN_PASSWORD="${SETUP_DB_PASSWORD:-}"
APP_DB="skyacs"
APP_USER="skyacs"
ENV_FILE="$ROOT_DIR/backend/.env"
CORS_ORIGINS="${SKYACS_CORS_ALLOWED_ORIGINS:-http://localhost:5173,http://127.0.0.1:5173}"

if [[ "$DB_HOST" == "localhost" && ${EUID} -eq 0 ]] && id postgres >/dev/null 2>&1; then
  PSQL=(runuser -u postgres -- psql -v ON_ERROR_STOP=1)
else
  PSQL=(env "PGPASSWORD=$DB_ADMIN_PASSWORD" psql -v ON_ERROR_STOP=1 -h "$DB_HOST" -p "$DB_PORT" -U "$DB_ADMIN_USER")
fi

echo "SKYACS database setup"
if [[ "$("${PSQL[@]}" -tAc "SELECT 1 FROM pg_database WHERE datname = '$APP_DB'")" == "1" ]]; then
  if [[ -f "$ENV_FILE" ]]; then
    if ! grep -q '^JWT_SECRET=' "$ENV_FILE"; then
      printf '\nJWT_SECRET=%s\n' "$(openssl rand -hex 32)" >>"$ENV_FILE"
    fi
    if ! grep -q '^PARAMETER_ENCRYPTION_KEY=' "$ENV_FILE"; then
      printf '\nPARAMETER_ENCRYPTION_KEY=%s\n' "$(openssl rand -hex 32)" >>"$ENV_FILE"
    fi
    if ! grep -q '^TRUSTED_PROXY_CIDRS=' "$ENV_FILE"; then
      printf 'TRUSTED_PROXY_CIDRS=127.0.0.1/32\n' >>"$ENV_FILE"
    fi
    if ! grep -q '^CWMP_TRUSTED_PROXY_CIDRS=' "$ENV_FILE"; then
      printf 'CWMP_TRUSTED_PROXY_CIDRS=127.0.0.1/32\n' >>"$ENV_FILE"
    fi
    if ! grep -q '^CONNECTION_REQUEST_ALLOWED_CIDRS=' "$ENV_FILE"; then
      printf 'CONNECTION_REQUEST_ALLOWED_CIDRS=\n' >>"$ENV_FILE"
    fi
    chmod 600 "$ENV_FILE"
    if [[ -n "${SKYACS_SERVICE_USER:-}" ]]; then
      chown "$SKYACS_SERVICE_USER":"$SKYACS_SERVICE_USER" "$ENV_FILE"
    fi
    echo "Database and backend/.env already exist; existing credentials were preserved."
    exit 0
  fi
  echo "Database exists but backend/.env is missing. Restore the original credentials or remove the database for a clean setup."
  exit 1
fi

APP_PASSWORD="$(openssl rand -hex 24)"
JWT_SECRET="$(openssl rand -hex 32)"
PARAMETER_ENCRYPTION_KEY="$(openssl rand -hex 32)"
INITIAL_ADMIN_PASSWORD="SKYACS-$(openssl rand -hex 12)"

if [[ "$("${PSQL[@]}" -tAc "SELECT 1 FROM pg_roles WHERE rolname = '$APP_USER'")" != "1" ]]; then
  "${PSQL[@]}" -c "CREATE USER $APP_USER WITH PASSWORD '$APP_PASSWORD'"
else
  "${PSQL[@]}" -c "ALTER USER $APP_USER WITH PASSWORD '$APP_PASSWORD'"
fi
"${PSQL[@]}" -c "CREATE DATABASE $APP_DB OWNER $APP_USER"
"${PSQL[@]}" -d "$APP_DB" -c "ALTER SCHEMA public OWNER TO $APP_USER"

install -m 600 /dev/null "$ENV_FILE"
cat >"$ENV_FILE" <<EOF
# Generated by setup.sh. Keep this file private.
PORT=7547
API_PORT=7548
CWMP_BIND_ADDR=127.0.0.1
API_BIND_ADDR=127.0.0.1
JWT_SECRET=$JWT_SECRET
PARAMETER_ENCRYPTION_KEY=$PARAMETER_ENCRYPTION_KEY
INITIAL_ADMIN_PASSWORD=$INITIAL_ADMIN_PASSWORD

DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_NAME=$APP_DB
DB_USER=$APP_USER
DB_PASSWORD=$APP_PASSWORD
DB_MAX_OPEN_CONNS=50
DB_MAX_IDLE_CONNS=10

CORS_ALLOWED_ORIGINS=$CORS_ORIGINS
TRUSTED_PROXY_CIDRS=127.0.0.1/32
CWMP_TRUSTED_PROXY_CIDRS=127.0.0.1/32
CONNECTION_REQUEST_ALLOWED_CIDRS=
FIRMWARE_UPLOAD_DIR=./uploads/firmware
EOF

if [[ -n "${SKYACS_SERVICE_USER:-}" ]]; then
  chown "$SKYACS_SERVICE_USER":"$SKYACS_SERVICE_USER" "$ENV_FILE"
fi

echo "Database created and backend/.env secured with mode 0600."
echo "Bootstrap login: admin / $INITIAL_ADMIN_PASSWORD"
echo "Store this password securely and rotate it after the first login."
